;/*FB_PKG_DELIM*/

__d("ApproveFromAnotherDeviceRootQuery_facebookRelayOperation",[],(function(t,n,r,o,a,i){a.exports="26582581714661574"}),null);
__d("FDSRelativeTimestamp.react",["BaseRelativeTimestamp.react","react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react"));function u(e){var t=e.date,n=e.format;return s.jsx(r("BaseRelativeTimestamp.react"),{date:t,format:n})}u.displayName=u.name+" [from "+i.id+"]",l.default=u}),98);
__d("FXFetaMigrationMomentNuxDialogQuery$Parameters",["cr:33478"],(function(t,n,r,o,a,i,l){"use strict";i.exports=n("cr:33478")}),34);
__d("FXFetaMigrationMomentNuxDialog.entrypoint",["FXFetaMigrationMomentNuxDialogQuery$Parameters","JSResourceForInteraction"],(function(t,n,r,o,a,i,l){"use strict";var e={getPreloadProps:function(){return{queries:{queryReference:{parameters:r("FXFetaMigrationMomentNuxDialogQuery$Parameters"),variables:{}}}}},root:r("JSResourceForInteraction")("FXFetaMigrationMomentNuxDialog.react").__setRef("FXFetaMigrationMomentNuxDialog.entrypoint")};l.default=e}),98);
__d("FXFetaMigrationMomentNuxDialogQuery_instagramRelayOperation",[],(function(t,n,r,o,a,i){a.exports="35565150386464944"}),null);
__d("FXFetaMigrationMomentNuxDialogQuery$Parameters.instagram",["FXFetaMigrationMomentNuxDialogQuery_instagramRelayOperation"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("FXFetaMigrationMomentNuxDialogQuery_instagramRelayOperation"),metadata:{},name:"FXFetaMigrationMomentNuxDialogQuery",operationKind:"query",text:null}};a.exports=e}),null);
__d("Href",[],(function(t,n,r,o,a,i){"use strict";function e(e){return typeof e=="object"&&e!=null&&e.url!=null?{type:"legacy",value:e}:{type:"modern",value:e}}i.getTypedHref=e}),66);
__d("PolarisFriendingConfirmationDialogQuery_instagramRelayOperation",[],(function(t,n,r,o,a,i){a.exports="27694905446797425"}),null);
__d("PolarisHasEditHighlightEnabled",["PolarisIsLoggedIn","PolarisUA"],(function(t,n,r,o,a,i,l){"use strict";function e(){return o("PolarisUA").isDesktop()&&o("PolarisIsLoggedIn").isLoggedIn()}l.hasEditHighlightEnabled=e}),98);
__d("PolarisIGCoreAvatar.react",["cx","PolarisFastLink.react","PolarisIGCoreConstants","joinClasses","react","react-compiler-runtime"],(function(t,n,r,o,a,i,l,s){"use strict";var e,u=e||(e=o("react"));function c(e){var t=e.children,n=e.className,o=e.href,a=e.onClick;switch(!0){case o!=null:return u.jsx(r("PolarisFastLink.react"),{className:n!=null?n:void 0,href:o,onClick:a,children:t});case a!=null:return u.jsx("button",{className:r("joinClasses")(n,"_aag4"),onClick:a,children:t});default:return u.jsx("span",{className:n,children:t})}}c.displayName=c.name+" [from "+i.id+"]";function d(e){var t=o("react-compiler-runtime").c(11),n=e.alt,a=e.dangerouslySetClassName,i=e.href,l=e.onClick,s=e.size,d=e.src,m=s===void 0?"medium":s,p=a!=null?a.__className:null,_;t[0]===Symbol.for("react.memo_cache_sentinel")?(_={className:"x1c9tyrk xeusxvb x1pahc9y x1ertn4p x972fbf x10w94by x1qhh985 x14e42zd xln7xf2 xk390pu xdj266r x14z9mp xat24cr x1lziwak xexx8yu xyri2b x18d9i69 x1c1uobl x11njtxf"},t[0]=_):_=t[0];var f=r("PolarisIGCoreConstants").AVATAR_SIZES[m],g=r("PolarisIGCoreConstants").AVATAR_SIZES[m],h;t[1]!==n||t[2]!==d||t[3]!==f||t[4]!==g?(h=u.jsx("img",babelHelpers.extends({alt:n},_,{height:f,src:d,width:g})),t[1]=n,t[2]=d,t[3]=f,t[4]=g,t[5]=h):h=t[5];var y;return t[6]!==p||t[7]!==i||t[8]!==l||t[9]!==h?(y=u.jsx(c,{className:p,href:i,onClick:l,children:h}),t[6]=p,t[7]=i,t[8]=l,t[9]=h,t[10]=y):y=t[10],y}l.default=d}),98);
__d("PolarisPostShareUtils",["PolarisLinkBuilder","PolarisShareIdParams","PolarisThirdPartyPlatformType","URI","nullthrows","polarisGetPostFromGraphMediaInterface"],(function(t,n,r,o,a,i,l){"use strict";var e;function s(e,t){return(t==null?void 0:t.isPrivate)!==!0&&e.viewerCanReshare===!0}function u(e){return e.igMediaSharingDisabled!==!0}function c(e){var t=r("nullthrows")(e.code);return o("polarisGetPostFromGraphMediaInterface").isClipsPost(e)?o("PolarisLinkBuilder").buildClipsMediaLink(t):o("PolarisLinkBuilder").buildMediaLink(t)}function d(t){var n=window.location.origin+c(t),a=t.shareUrls,i=a!=null?a[o("PolarisThirdPartyPlatformType").PolarisThirdPartyPlatformType.COPY_LINK]:null;if(i!=null){var l=(e||(e=r("URI"))).tryParseURI(i);if(l==null)return i;var s=babelHelpers.extends({},l.getQueryData());if(o("PolarisShareIdParams").shouldEmitCurrentShareIdParam()&&s[o("PolarisShareIdParams").CURRENT_SHARE_ID_PARAM]==null){var u=o("PolarisShareIdParams").getShareIdFromParams(s);u!=null&&(s[o("PolarisShareIdParams").CURRENT_SHARE_ID_PARAM]=u)}return l.setQueryData(babelHelpers.extends({utm_source:"ig_web_copy_link"},s)).toStringRawQuery()}return n+"?utm_source=ig_web_copy_link"}l.getIsShareable=s,l.getIsMediaQuarantinedForShare=u,l.getShareURL=c,l.getCopyUrl=d}),98);
__d("PolarisWAISTDialogItem.react",["IGDSDialogItem.react","IGDSText.react","PolarisGenericStrings","react","react-compiler-runtime"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react"));function u(e){var t=o("react-compiler-runtime").c(3),n=e.onClick,a;t[0]===Symbol.for("react.memo_cache_sentinel")?(a=s.jsx(r("IGDSText.react"),{zeroMargin:!1,children:o("PolarisGenericStrings").WAIST_TITLE}),t[0]=a):a=t[0];var i;return t[1]!==n?(i=s.jsx(o("IGDSDialogItem.react").IGDSDialogItem,{onClick:n,testid:void 0,children:a}),t[1]=n,t[2]=i):i=t[2],i}l.default=u}),98);
__d("XPolarisEditBoostedAdControllerRouteBuilder",["jsRouteBuilder"],(function(t,n,r,o,a,i,l){var e=r("jsRouteBuilder")("/b/edit_boosted_ad/",Object.freeze({context:"ads_manager_edit_promote_unknown"}),void 0),s=e;l.default=s}),98);
__d("XPolarisPostControllerRouteBuilder",["jsRouteBuilder"],(function(t,n,r,o,a,i,l){var e=r("jsRouteBuilder")("/{permalink_key}/{shortcode}/{?slug}/",Object.freeze({chaining:!1,preserve_img_index:!1,viewer:!1,show_insights:!1}),void 0),s=e;l.default=s}),98);
__d("hasInteractiveAncestor",[],(function(t,n,r,o,a,i){"use strict";var e=["button","dialog","select","input","textarea","a","iframe","embed","label",'[role="button"]','[role="checkbox"]','[role="combobox"]','[role="dialog"]','[role="link"]','[role="listbox"]','[role="menuitem"]','[role="menuitemcheckbox"]','[role="menuitemradio"]','[role="option"]','[role="radio"]','[role="scrollbar"]','[role="searchbox"]','[role="slider"]','[role="spinbutton"]','[role="switch"]','[role="tab"]','[role="tablist"]','[role="textbox"]','[role="treeitem"]',"[data-pressable-container]"].join(","),l=['[aria-readonly="true"]'].join(",");function s(t,n){for(var r=t,o=!1;r!=null&&!r.matches(n)&&r!==document.body&&(o=r.matches(e)&&!r.matches(l),!o);)r=r.parentElement;return o}function u(t,n){for(var r=t,o=!1;r!=null&&r!==n&&r!==document.body&&(o=r.matches(e)&&!r.matches(l),!o);)r=r.parentElement;return o}function c(t){return t.matches(e)}i.hasInteractiveAncestorUpToSelector=s,i.hasInteractiveAncestorUpToParent=u,i.isInteractive=c}),66);