;/*FB_PKG_DELIM*/

__d("XPlatReactTextEncoder",[],(function(t,n,r,o,a,i){"use strict";var e=self.TextEncoder;i.TextEncoder=e}),66);
__d("base64Binary",["invariant"],(function(t,n,r,o,a,i,l,s){"use strict";function e(e){for(var t="",n=0;n<e.byteLength;n+=3){var r=e.subarray(n,n+3);t+=m(r)}var o=(e.byteLength+2)%3;return t.slice(0,t.length+o-2)+"==".slice(o)}function u(e){var t,n;e.length%4===0||s(0,51156);for(var r=e.length/4,o=(t=(n=e.match(/={0,2}$/))==null?void 0:n[0].length)!=null?t:0,a=new Uint8Array(r*3-o),i=0;i<r;i++){var l=p(e.slice(i*4,i*4+4));a.set(l.subarray(0,a.byteLength-i*3),i*3)}return a}var c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/",d=">___?456789:;<=___\0___\0\x07\b	\n\v\f\r______\x1B !\"#$%&'()*+,-./0123";function m(e){var t,n,r=e[0]<<16|((t=e[1])!=null?t:0)<<8|((n=e[2])!=null?n:0);return String.fromCharCode(c.charCodeAt(r>>>18),c.charCodeAt(r>>>12&63),c.charCodeAt(r>>>6&63),c.charCodeAt(r&63))}function p(e){var t=d.charCodeAt(e.charCodeAt(0)-43)<<18|d.charCodeAt(e.charCodeAt(1)-43)<<12|d.charCodeAt(e.charCodeAt(2)-43)<<6|d.charCodeAt(e.charCodeAt(3)-43);return new Uint8Array([t>>>16,t>>>8&255,t&255])}l.encode=e,l.decode=u}),98);
__d("Base64Utils",["XPlatReactTextEncoder","base64Binary"],(function(t,n,r,o,a,i,l){"use strict";function e(e){return o("base64Binary").encode(new(o("XPlatReactTextEncoder")).TextEncoder().encode(e))}function s(e){return o("base64Binary").encode(new Uint8Array(e))}function u(e){return o("base64Binary").decode(e).buffer}l.encodeUnicode=e,l.fromArrayBuffer=s,l.toArrayBuffer=u}),98);
__d("UnicodeUtils",["invariant"],(function(t,n,r,o,a,i,l,s){"use strict";var e=55296,u=56319,c=56320,d=57343,m=/[\uD800-\uDFFF]/;function p(t){return e<=t&&t<=d}function _(t,n){if(0<=n&&n<t.length||s(0,1346,n,t.length),n+1===t.length)return!1;var r=t.charCodeAt(n),o=t.charCodeAt(n+1);return e<=r&&r<=u&&c<=o&&o<=d}function f(e){return m.test(e)}function g(e,t){var n=p(e.charCodeAt(t));return n?2:1}function h(e){if(!f(e))return e.length;for(var t=0,n=0;n<e.length;n+=g(e,n))t++;return t}function y(e,t){return b(e,t,t+1)}function C(e,t,n){var r=t||0,o=n===void 0?1/0:n||0;if(!f(e))return e.substr(r,o);var a=e.length;if(a<=0||r>a||o<=0)return"";var i=0;if(r>0){for(;r>0&&i<a;r--)i+=g(e,i);if(i>=a)return""}else if(t<0){for(i=a;r<0&&0<i;r++)i-=g(e,i-1);i<0&&(i=0)}var l=a;if(o<a)for(l=i;o>0&&l<a;o--)l+=g(e,l);return e.substring(i,l)}function b(e,t,n){var r=t||0,o=n===void 0?1/0:n||0;r<0&&(r=0),o<0&&(o=0);var a=Math.abs(o-r);return r=r<o?r:o,C(e,r,a)}function v(e){for(var t=[],n=0;n<e.length;n+=g(e,n))t.push(e.codePointAt(n));return t}l.isCodeUnitInSurrogateRange=p,l.isSurrogatePair=_,l.hasSurrogateUnit=f,l.getUTF16Length=g,l.strlen=h,l.charAt=y,l.substr=C,l.substring=b,l.getCodePoints=v}),98);
__d("baseTextWithEntitiesApplyRenderers",["react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u=s.Fragment;function c(e,t,n,r,o,a,i,l,c,d){var m=e.__typename,p=Object.prototype.hasOwnProperty.call(l,m)?l[m].concat(c):c;return s.jsx(u,{children:p&&p.length>0?p.reduce(function(r,a){return a(r,e,n,o,t,d)},a):r},i)}c.displayName=c.name+" [from "+i.id+"]",l.default=c}),98);
__d("baseTextWithEntitiesApplyTextTransforms",[],(function(t,n,r,o,a,i){"use strict";function e(e,t){return t!=null?t.reduce(function(e,t){return t(e)},e):e}e.displayName=e.name+" [from "+a.id+"]",i.default=e}),66);
__d("baseTextWithEntitiesProcessRange",["UnicodeUtils","baseTextWithEntitiesApplyRenderers","baseTextWithEntitiesApplyTextTransforms","react"],(function(t,n,r,o,a,i,l){"use strict";var e,s,u=e||(e=o("react")),c=u.Fragment;function d(e,t,n,a,i,l,d,m,p,_,f,g){var h=(s||(s=o("UnicodeUtils"))).substr(e,t,n-t),y=p.length;h.length>0&&m.push(u.jsx(c,{children:r("baseTextWithEntitiesApplyTextTransforms")(h,_)},"c"+t+"_"+y+"_"+g));var C=p.pop(),b=h.trim().length>0&&h.trim()===e.trim();return p[p.length-1].subElements.push(r("baseTextWithEntitiesApplyRenderers")(a,i,l,m,h,m,t+"_"+y+"_"+g,d,f,b)),C}l.default=d}),98);
__d("baseTextWithEntitiesSortRanges",[],(function(t,n,r,o,a,i){"use strict";function e(e){return Array.from(e).sort(function(e,t){return e.offset-t.offset||t.length-e.length})}i.default=e}),66);
__d("BaseCometTextWithEntitiesBase.react",["UnicodeUtils","baseTextWithEntitiesApplyRenderers","baseTextWithEntitiesApplyTextTransforms","baseTextWithEntitiesProcessRange","baseTextWithEntitiesSortRanges","react"],(function(t,n,r,o,a,i,l){"use strict";var e,s,u=e||(e=o("react")),c=u.Fragment;function d(e){for(var t,n=e.ranges,a=n===void 0?[]:n,i=e.renderers,l=e.transforms,d=l===void 0?[]:l,m=e.text,p=e.disableRangeSort,_=p===void 0?!1:p,f=i!=null?i:{},g=0,h=(t=Object.prototype.hasOwnProperty.call(f,"*")?f["*"]:[])!=null?t:[],y=_?a:r("baseTextWithEntitiesSortRanges")(a),C=[{entity:{__typename:""},entity_is_weak_reference:!1,entityType:"",length:m.length,offset:0,subElements:[]}],b=0;b<y.length;++b){var v=y[b],S=v.entity,R=v.entity_is_weak_reference,L=v.entity_type,E=v.length,k=v.offset;if(g>=m.length||k>m.length)break;for(var I=C[C.length-1],T=I.entity,D=I.entity_is_weak_reference,x=I.entityType,$=I.length,P=I.offset,N=I.subElements,M=P+$;M<=k&&C.length>1;){r("baseTextWithEntitiesProcessRange")(m,g,M,T,D,x,f,N,C,d,h,b),g=M;var w=C[C.length-1];T=w.entity,D=w.entity_is_weak_reference,x=w.entityType,$=w.length,P=w.offset,N=w.subElements,M=P+$}if(g<k&&(C[C.length-1].subElements.push(u.jsx(c,{children:r("baseTextWithEntitiesApplyTextTransforms")((s||(s=o("UnicodeUtils"))).substr(m,g,k-g),d)},"c"+g+"_"+C.length)),g=k),P<=k&&M>=k+E)C.push({entity:S,entity_is_weak_reference:R!=null?R:null,entityType:L!=null?L:null,length:E,offset:k,subElements:[]});else{var A=(s||(s=o("UnicodeUtils"))).substr(m,k,E),F=r("baseTextWithEntitiesApplyTextTransforms")(A,d),O=A.trim().length>0&&A.trim()===m.trim();C[C.length-1].subElements.push(r("baseTextWithEntitiesApplyRenderers")(S,R!=null?R:null,L!=null?L:null,A,A,F,g+"_"+C.length,f,h,O)),g=k+E}}for(;C.length>1;){var B=C[C.length-1],W=B.entity,q=B.entity_is_weak_reference,U=B.entityType,V=B.length,H=B.offset,G=B.subElements,z=H+V;r("baseTextWithEntitiesProcessRange")(m,g,z,W,q,U,f,G,C,d,h,C.length),g=z}if(g<m.length){var j=C[C.length-1].subElements;j.push(u.jsx(c,{children:r("baseTextWithEntitiesApplyTextTransforms")((s||(s=o("UnicodeUtils"))).substr(m,g),d)},"c"+g))}return u.jsx(u.Fragment,{children:C[C.length-1].subElements})}d.displayName=d.name+" [from "+i.id+"]",l.default=d}),98);
__d("baseTextWithEntitiesAdjustRanges",[],(function(t,n,r,o,a,i){"use strict";function e(e,t,n){return e.map(function(e){return babelHelpers.extends({},e,{offset:e.offset-t})}).filter(function(e){return e.offset>=0&&e.offset<n})}i.default=e}),66);
__d("baseTextWithEntitiesFilterRanges",[],(function(t,n,r,o,a,i){"use strict";function e(e){for(var t=[],n=0;n<e.length;n++){var r=e[n];if(r!=null&&r.offset!=null&&r.length!=null&&r.entity!=null&&r.entity.__typename!=null){var o;t.push({entity:r.entity,entity_is_weak_reference:(o=r.entity_is_weak_reference)!=null?o:null,length:r.length,offset:r.offset})}}return t}i.default=e}),66);
__d("baseTextWithEntitiesSplitRangesAndTextIntoParagraphs",["UnicodeUtils","baseTextWithEntitiesAdjustRanges"],(function(t,n,r,o,a,i,l){"use strict";var e;function s(t){var n=t.ranges,a=t.text,i=0;return a.split("\n").map(function(t){var a=r("baseTextWithEntitiesAdjustRanges")(n,i,(e||(e=o("UnicodeUtils"))).strlen(t));return i+=e.strlen(t)+1,{ranges:a,text:t}}).filter(function(e){return e.text.trim()!==""})}function u(t,n){var a=t.ranges,i=t.text,l=0;return i.split(/(?=\n\s*\n)/).map(function(t){var i,u,c,d=(i=t.match(/(^\n\s*\n)?([^]*$)/))!=null?i:[],m=(u=d[1])!=null?u:"",p=(c=d[2])!=null?c:t,_=r("baseTextWithEntitiesAdjustRanges")(a,l+m.length,(e||(e=o("UnicodeUtils"))).strlen(p));return l+=e.strlen(t),n?s({ranges:_,text:p}):{ranges:_,text:p}})}l.default=u}),98);
__d("getTextDirectionAttribute",["cr:1080422"],(function(t,n,r,o,a,i,l){"use strict";function e(e){var t="auto";return n("cr:1080422")!=null&&window!=null&&(t=n("cr:1080422").isDirectionRTL(e)?"rtl":"ltr"),t}l.default=e}),98);
__d("translatedServerString",[],(function(t,n,r,o,a,i){"use strict";function e(e){return e}i.default=e}),66);
__d("useCustomEqualityMemo",["react","useUnsafeRef_DEPRECATED"],(function(t,n,r,o,a,i,l){"use strict";var e,s,u=(s||(s=o("react"))).useEffect;function c(t,n){var o=(e||(e=r("useUnsafeRef_DEPRECATED")))(t),a=n(o.current,t)?o.current:t;return u(function(){o.current=a},[a]),a}l.default=c}),98);
__d("useShallowEqualMemo",["shallowEqual","useCustomEqualityMemo"],(function(t,n,r,o,a,i,l){"use strict";function e(e){return r("useCustomEqualityMemo")(e,r("shallowEqual"))}l.default=e}),98);